services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "./deploy/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
